// export * from './components/Breadcrumb';
// export * from './components/BreadcrumbItem';
// export * from './components/Button';
// export * from './components/ButtonGroup';
// export * from './components/Card';
// export * from './components/Checkbox';
// export * from './components/CheckboxButtons';
// export * from './components/CheckboxGroup';
// export * from './components/Collapsible';
// export * from './components/CollapsibleItem';
// export * from './components/Column';
// export * from './components/Container';
// export * from './components/Dropdown';
// export * from './components/DropdownDivider';
// export * from './components/DropdownItem';
// export * from './components/ExpandTransition';
// export * from './components/Form';
// export * from './components/FormGroup';
// export * from './components/FormError';
// export * from './components/FormLabel';
// export * from './components/HamburgerMenu';
// export * from './components/Header';
// export * from './components/Icon';
// export * from './components/Input';
// export * from './components/Layout';
// export * from './components/LayoutAside';
// export * from './components/LayoutContent';
// export * from './components/LayoutFooter';
// export * from './components/LayoutHeader';
// export * from './components/ListGroup';
// export * from './components/ListGroupItem';
// export * from './components/Loader';
// export * from './components/Mark';
// export * from './components/Media';
// export * from './components/Modal';
// export * from './components/ModalContainer';
// export * from './components/Nav';
// export * from './components/NavItem';
// export * from './components/Navbar';
// export * from './components/NavbarBrand';
// export * from './components/NavbarCollapsible';
// export * from './components/NumberInput';
// export * from './components/Pagination';
// export * from './components/Popover';
// export * from './components/Progress';
// export * from './components/ProgressBar';
// export * from './components/Radio';
// export * from './components/RadioButtons';
// export * from './components/RadioGroup';
// export * from './components/Row';
// export * from './components/Select';
// export * from './components/SelectOption';
// export * from './components/Sidebar';
// export * from './components/Table';
// export * from './components/Tabs';
// export * from './components/Tab';
// export * from './components/TabTitle';
// export * from './components/Textarea';
// export * from './components/Toast';
// export * from './components/ToastContainer';
// export * from './components/Toggle';
// export * from './components/Tooltip';
// export * from './components/utils';

import { useAlertTheme } from '@inkline/component-alert';
import { useBadgeTheme } from '@inkline/component-badge';
import { useBreadcrumbTheme } from '@inkline/component-breadcrumb';
import { useButtonTheme } from '@inkline/component-button';
import { useLoaderTheme } from '@inkline/component-loader';
// import { useBadgeTheme } from './components/Badge/theme';
// import { useBreadcrumbTheme } from './components/Breadcrumb/theme';
// import { useBreadcrumbItemTheme } from './components/BreadcrumbItem/theme';
// import { useButtonTheme } from './components/Button/theme';
// import { useButtonGroupTheme } from './components/ButtonGroup/theme';
// import { useCardTheme } from './components/Card/theme';

export function useThemeComponents() {
    useAlertTheme();
    useBadgeTheme();
    useBreadcrumbTheme();
    useButtonTheme();
    // useBadgeTheme();
    // useBreadcrumbTheme();
    // useBreadcrumbItemTheme();
    // useButtonTheme();
    // useButtonGroupTheme();
    // useCardTheme();
    useLoaderTheme();
}
