export type ColorModePropValue = {
    light: string;
    dark: string;
};

export type ComponentProps = {
    alignItems?: string;
    alignContent?: string;
    alignSelf?: string;
    background?: string | ColorModePropValue;
    border?: string;
    borderWidth?: string;
    borderTopWidth?: string;
    borderRightWidth?: string;
    borderBottomWidth?: string;
    borderLeftWidth?: string;
    borderStyle?: string;
    borderTopStyle?: string;
    borderRightStyle?: string;
    borderBottomStyle?: string;
    borderLeftStyle?: string;
    borderColor?: string | ColorModePropValue;
    borderTopColor?: string | ColorModePropValue;
    borderRightColor?: string | ColorModePropValue;
    borderBottomColor?: string | ColorModePropValue;
    borderLeftColor?: string | ColorModePropValue;
    borderRadius?: string;
    borderTopLeftRadius?: string;
    borderTopRightRadius?: string;
    borderBottomRightRadius?: string;
    borderBottomLeftRadius?: string;
    boxShadow?: string;
    color?: string | ColorModePropValue;
    display?: string;
    fontSize?: string;
    fontWeight?: string;
    margin?: string;
    marginTop?: string;
    marginRight?: string;
    marginBottom?: string;
    marginLeft?: string;
    marginX?: string;
    marginY?: string;
    maxWidth?: string;
    maxHeight?: string;
    minWidth?: string;
    minHeight?: string;
    overflow?: string;
    overflowX?: string;
    overflowY?: string;
    textAlign?: string;
    textOverflow?: string;
    whiteSpace?: string;
    wordBreak?: string;
    flexDirection?: string;
    flexWrap?: string;
    gap?: string;
    gapX?: string;
    gapY?: string;
    gridTemplateColumns?: string;
    gridTemplateRows?: string;
    gridColumnGap?: string;
    gridRowGap?: string;
    gridColumnStart?: string;
    gridColumnEnd?: string;
    gridRowStart?: string;
    gridRowEnd?: string;
    height?: string;
    justifyContent?: string;
    padding?: string;
    paddingTop?: string;
    paddingRight?: string;
    paddingBottom?: string;
    paddingLeft?: string;
    paddingX?: string;
    paddingY?: string;
    size?: string;
    width?: string;
    [key: string]: string | string[] | boolean | number | ColorModePropValue | undefined;
};
