---
plugins:
    - stylelint-scss
extends:
    - stylelint-config-standard
    - stylelint-config-recommended-scss
rules:
    indentation: 4
    custom-property-empty-line-before: null
    value-keyword-case: null
    no-descending-specificity: null
    color-hex-length: null
    at-rule-empty-line-before:
        -   always
        -   ignore:
                -   after-comment
                -   first-nested
                -   blockless-after-blockless
            ignoreAtRules:
                -   else
                -   else if
                -   each
    block-closing-brace-newline-after: null
    value-list-max-empty-lines: null
