packages:
    - packages/*
    - packages/components/*
    - packages/e2e/*
    - packages/integrations/*
    - packages/plugin/*
    - packages/plugin/addons/*
    - packages/tooling/*
catalog:
    '@types/node': ^20.14.5
    '@types/shelljs': ^0.8.15
    '@eslint/js': ^9.3.0
    '@fullhuman/postcss-purgecss': ^6.0.0
    '@vitejs/plugin-vue': ^5.1.4
    '@vitest/coverage-v8': ^2.1.1
    '@vue/runtime-core': ^3.5.8
    '@vue/test-utils': ^2.4.6
    '@nuxt/kit': ^3.13.2
    '@nuxt/module-builder': ^0.8.4
    '@nuxt/schema': ^3.13.2
    '@testing-library/jest-dom': ^6.5.0
    '@testing-library/vue': ^8.1.0
    chalk: ^4.1.2
    chokidar: ^3.6.0
    commander: ^12.0.0
    eslint: ^9.3.0
    jsdom: ^25.0.1
    normalize.css: ^8.0.1
    np: ^10.0.1
    nodemon: ^3.1.7
    nuxt: ^3.13.2
    prettier: ^3.2.5
    shelljs: ^0.8.5
    stylelint: ^16.5.0
    tsup: ^8.3.0
    tsx: ^4.19.1
    turbo: ^2.1.3
    typescript: ^5.5.3
    type-fest: ^4.26.1
    unplugin: ^1.14.1
    vite: ^5.4.1
    vite-plugin-dts: ^4.2.2
    vite-plugin-inspect: ^0.8.7
    vitest: ^2.1.1
    vue: ^3.5.8
    vue-tsc: ^2.1.6

