packages:
    - docs
    - packages/*
    - packages/engine/*
    - packages/ui/*
    - packages/ui/components/*
    - packages/ui/addons/*
    - packages/integrations/*
    - packages/tooling/*
    - e2e/*
    - storybook
catalog:
    '@types/node': ^20.14.5
    '@types/color': ^4.2.0
    '@types/shelljs': ^0.8.15
    '@eslint/js': ^9.19.0
    '@fullhuman/postcss-purgecss': ^7.0.2
    '@vitejs/plugin-vue': ^5.2.1
    '@vitest/coverage-v8': ^3.0.4
    '@vue/runtime-core': ^3.5.8
    '@vue/test-utils': ^2.4.6
    '@nuxt/kit': ^3.15.4
    '@nuxt/module-builder': ^0.8.4
    '@nuxt/schema': ^3.15.4
    '@nuxt/content': ^3.0.1
    '@testing-library/jest-dom': ^6.6.3
    '@testing-library/vue': ^8.1.0
    chalk: ^4.1.2
    chokidar: ^3.6.0
    commander: ^13.1.0
    eslint: ^9.19.0
    fast-glob: ^3.3.3
    jsdom: ^26.0.0
    normalize.css: ^8.0.1
    np: ^6.2.4
    nodemon: ^3.1.9
    nuxt: ^3.15.4
    prettier: ^3.4.2
    shelljs: ^0.8.5
    stylelint: ^16.14.1
    tsup: ^8.3.6
    tsx: ^4.19.2
    turbo: ^2.3.4
    typescript: ^5.7.3
    type-fest: ^4.33.0
    unplugin: ^2.1.2
    vite: ^6.0.11
    vite-plugin-dts: ^4.5.0
    vite-plugin-inspect: ^0.8.7
    vitest: ^3.0.4
    vue: ^3.5.8
    vue-tsc: ^2.2.0
    vue-router: ^4.5.0

