packages:
    - packages/*
    - packages/tooling/*
    - packages/e2e/*
    - packages/integrations/*
catalog:
    '@types/node': ^20.14.5
    '@eslint/js': ^9.3.0
    '@vitejs/plugin-vue': ^5.1.4
    '@vitest/coverage-v8': ^2.1.1
    '@nuxt/kit': ^3.13.2
    '@nuxt/module-builder': ^0.8.4
    '@nuxt/schema': ^3.13.2
    chokidar: ^3.6.0
    eslint: ^9.3.0
    np: ^10.0.1
    nuxt: ^3.13.2
    prettier: ^3.2.5
    stylelint: ^16.5.0
    typescript: ^5.5.3
    type-fest: ^4.26.1
    unplugin: ^1.14.1
    vite: ^5.4.1
    vite-plugin-dts: ^4.2.2
    vite-plugin-inspect: ^0.8.7
    vitest: ^2.1.1

