packages:
  - apps/*
  - packages/*
  - ui/*
  - tools/*

catalog:
  concurrently: ^9
  "@analogjs/vite-plugin-angular": ^2.5.1
  "@angular-eslint/eslint-plugin": ^21.4.0
  "@angular-eslint/template-parser": ^21.4.0
  "@angular/build": ^21.2.11
  "@angular/compiler": ^21.2.13
  "@angular/compiler-cli": ^21.2.13
  "@sveltejs/vite-plugin-svelte": ^7.1.2
  "@tsdown/css": ^0.22.0
  "@types/node": ^24
  "@typescript-eslint/parser": ^8.59.3
  "@vitejs/plugin-react": ^6.0.2
  "@vitejs/plugin-vue": ^6.0.7
  "@vitest/coverage-v8": ^4.1.5
  jsdom: ^26.1.0
  eslint: ^9.39.4
  eslint-plugin-astro: ^1.7.0
  eslint-plugin-qwik: ^1.19.2
  eslint-plugin-solid: ^0.14.5
  eslint-plugin-svelte: ^3.17.1
  eslint-plugin-vue: ^10.9.1
  oxlint: ^1.64.0
  rollup-plugin-svelte: ^7.2.3
  storybook: ^10
  storybook-framework-qwik: ^0.6.0
  storybook-solidjs-vite: ^10
  "@storybook/angular": ^10
  "@storybook-astro/framework": ^1.2.0
  "@storybook/addon-a11y": ^10
  "@storybook/addon-docs": ^10
  "@storybook/react-vite": ^10
  "@storybook/svelte-vite": ^10
  "@storybook/vue3-vite": ^10
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plugin-solid: ^2.11.12
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vue-eslint-parser: ^10.4.0

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
