import { defineConfig } from '@inkline/core';
import { useTheme } from '@inkline/theme';

import { useAlertTheme } from '@inkline/component-alert';
import { useBadgeTheme } from '@inkline/component-badge';
import { useBreadcrumbTheme, useBreadcrumbItemTheme } from '@inkline/component-breadcrumb';
import { useButtonTheme } from '@inkline/component-button';
import { useButtonGroupTheme } from '@inkline/component-button-group';
import { useCardTheme } from '@inkline/component-card';
import { useCheckboxTheme, useCheckboxGroupTheme } from '@inkline/component-checkbox';
import { useFormGroupTheme } from '@inkline/component-form-group';
import { useExpandTheme } from '@inkline/component-expand';
import { useGridTheme } from '@inkline/component-grid';
import { useIconTheme } from '@inkline/component-icon';
import { useInputTheme } from '@inkline/component-input';
import { useLoaderTheme } from '@inkline/component-loader';
import { useMediaTheme } from '@inkline/component-media';
import { useModalTheme, useModalContainerTheme } from '@inkline/component-modal';
import { useNavTheme, useNavItemTheme } from '@inkline/component-nav';
import { usePopoverTheme } from '@inkline/component-popover';
import { useRadioTheme, useRadioGroupTheme } from '@inkline/component-radio';
import { useToastTheme, useToastContainerTheme } from '@inkline/component-toast';
import { useToggleTheme } from '@inkline/component-toggle';
import { useTooltipTheme } from '@inkline/component-tooltip';

export default defineConfig((options) => {
    useTheme(options);
    useAlertTheme(options);
    useBadgeTheme(options);
    useBreadcrumbTheme(options);
    useBreadcrumbItemTheme(options);
    useButtonTheme(options);
    useButtonGroupTheme(options);
    useCardTheme(options);
    useCheckboxTheme(options);
    useCheckboxGroupTheme(options);
    useFormGroupTheme(options);
    useExpandTheme(options);
    useGridTheme(options);
    useIconTheme(options);
    useInputTheme(options);
    useLoaderTheme(options);
    useMediaTheme(options);
    useModalTheme(options);
    useModalContainerTheme(options);
    usePopoverTheme(options);
    useNavTheme(options);
    useNavItemTheme(options);
    useRadioTheme(options);
    useRadioGroupTheme(options);
    useToastTheme(options);
    useToastContainerTheme(options);
    useToggleTheme(options);
    useTooltipTheme(options);
});
