import type { SlotValue, ScopedSlotContent } from "../../define.ts";

export const BANNER =
  "// AUTO-GENERATED by @inkline/storybook — DO NOT EDIT.\n" +
  "// Edit the single-source definition in ui/components/stories/ and regenerate.\n";

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

/**
 * Guards values that are emitted as raw code (not string literals): the
 * component binding and every story export name. An invalid identifier would
 * produce a story file that fails to parse, so fail fast with a clear message.
 */
export function assertIdentifier(value: string, label: string): void {
  if (!IDENTIFIER.test(value)) {
    throw new Error(
      `Invalid ${label} ${JSON.stringify(value)}: must be a valid JavaScript identifier.`,
    );
  }
}

/** Compact, deterministic serialization for `args`/`argTypes` object literals. */
export function serializeArgs(value: unknown): string {
  return JSON.stringify(value);
}

export function isScoped(value: SlotValue): value is ScopedSlotContent {
  return typeof value !== "string";
}

export function mergeSlots(
  meta: Readonly<Record<string, SlotValue>> | undefined,
  story: Readonly<Record<string, SlotValue>> | undefined,
): Readonly<Record<string, SlotValue>> | undefined {
  if (!meta && !story) return undefined;
  if (!story) return meta;
  if (!meta) return story;
  return { ...meta, ...story };
}

export function toKebabCase(str: string): string {
  return str
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1-$2")
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .toLowerCase();
}

export function getSlotImports(target: string): readonly string[] {
  switch (target) {
    case "react":
      return ['import { createElement } from "react";'];
    case "vue":
      return ['import { h } from "vue";'];
    case "solid":
      return [
        'import { mergeProps } from "solid-js";',
        'import { createComponent } from "solid-js/web";',
      ];
    case "angular":
      return ['import { argsToTemplate } from "@storybook/angular";'];
    default:
      return [];
  }
}

export function buildSlotRender(
  component: string,
  slots: Readonly<Record<string, SlotValue>>,
  target: string,
): string | null {
  switch (target) {
    case "react":
      return buildReactRender(component, slots);
    case "vue":
      return buildVueRender(component, slots);
    case "solid":
      return buildSolidRender(component, slots);
    case "angular":
      return buildAngularRender(component, slots);
    default:
      return null;
  }
}

function buildReactRender(component: string, slots: Readonly<Record<string, SlotValue>>): string {
  const defaultSlot = slots["default"];
  const defaultIsScoped = defaultSlot != null && isScoped(defaultSlot);

  const renderProps: string[] = [];
  for (const [name, value] of Object.entries(slots)) {
    if (name === "default" && !defaultIsScoped) continue;
    const propName = `render${name[0].toUpperCase()}${name.slice(1)}`;
    if (isScoped(value)) {
      renderProps.push(`${propName}: (${value.params.join(", ")}) => ${value.content}`);
    } else {
      renderProps.push(`${propName}: () => ${JSON.stringify(value)}`);
    }
  }

  const propsExpr = renderProps.length > 0 ? `{ ...args, ${renderProps.join(", ")} }` : "args";
  const childrenArg =
    defaultSlot && !defaultIsScoped ? `, ${JSON.stringify(defaultSlot as string)}` : "";

  return `(args) => createElement(${component}, ${propsExpr}${childrenArg})`;
}

function buildVueRender(component: string, slots: Readonly<Record<string, SlotValue>>): string {
  const slotEntries = Object.entries(slots).map(([name, value]) => {
    if (isScoped(value)) {
      return `${name}: ({ ${value.params.join(", ")} }) => ${value.content}`;
    }
    return `${name}: () => ${JSON.stringify(value)}`;
  });

  return `(args) => h(${component}, args, { ${slotEntries.join(", ")} })`;
}

function buildSolidRender(component: string, slots: Readonly<Record<string, SlotValue>>): string {
  const entries = Object.entries(slots).map(([name, value]) => {
    const propName = name === "default" ? "children" : name;
    if (isScoped(value)) {
      return `${propName}: (${value.params.join(", ")}) => ${value.content}`;
    }
    return `${propName}: ${JSON.stringify(value)}`;
  });

  return `(args) => createComponent(${component}, mergeProps(args, { ${entries.join(", ")} }))`;
}

function buildAngularRender(component: string, slots: Readonly<Record<string, SlotValue>>): string {
  const tag = toKebabCase(component);
  const parts: string[] = [];

  for (const [name, value] of Object.entries(slots)) {
    if (name === "default") continue;
    if (!isScoped(value)) {
      parts.push(`<ng-container slot="${name}">${value}</ng-container>`);
    }
  }

  const defaultSlot = slots["default"];
  if (defaultSlot && !isScoped(defaultSlot)) {
    parts.push(defaultSlot);
  }

  const content = parts.join("");
  return `(args) => ({ props: args, template: '<${tag} ' + argsToTemplate(args) + '>${content}</${tag}>' })`;
}
