import type { ResolvedRenderImport } from "../index.ts";

export const BANNER =
  "// AUTO-GENERATED by @inkline/storybook — DO NOT EDIT.\n" +
  "// Edit the single-source definition alongside the component and regenerate.\n";

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

/**
 * Guards values that are emitted as raw code (not string literals): the
 * component binding and every story export name. An invalid identifier would
 * produce a story file that fails to parse, so fail fast with a clear message.
 */
export function assertIdentifier(value: string, label: string): void {
  if (!IDENTIFIER.test(value)) {
    throw new Error(
      `Invalid ${label} ${JSON.stringify(value)}: must be a valid JavaScript identifier.`,
    );
  }
}

/** Compact, deterministic serialization for `args`/`argTypes` object literals. */
export function serializeArgs(value: unknown): string {
  return JSON.stringify(value);
}

/**
 * Build the render-import statement lines, deduplicated.
 *
 * Several stories may share one render source — e.g. a `Default` story that reuses another story's
 * render `.ink.tsx`. Because the local binding is derived from the render file's basename, those
 * stories produce `ResolvedRenderImport` entries with an identical local name and import path.
 * Emitting each verbatim would declare the same identifier twice, which crashes the whole story
 * module ("Identifier 'X' has already been declared"). Collapse exact duplicates to a single import;
 * the per-story render expressions still resolve to the shared binding.
 */
export function renderImportLines(
  renderImports: readonly ResolvedRenderImport[],
  hasDefaultExport: boolean,
): string[] {
  const seen = new Set<string>();
  const lines: string[] = [];
  for (const ri of renderImports) {
    assertIdentifier(ri.localName, "render import");
    const line = hasDefaultExport
      ? `import ${ri.localName} from "${ri.importPath}";`
      : `import { ${ri.exportedName} as ${ri.localName} } from "${ri.importPath}";`;
    if (seen.has(line)) continue;
    seen.add(line);
    lines.push(line);
  }
  return lines;
}
