// Auto-generated by @styleframe/plugin - DO NOT EDIT

declare module "virtual:styleframe" {
    import type { Styleframe } from "@styleframe/core";

    /** Returns the global styleframe instance from styleframe.config.ts */
    export function styleframe(): Styleframe;

    export type BadgeProps = { color?: "primary" | "secondary" | "success" | "info" | "warning" | "error" | "light" | "dark" | "neutral"; variant?: "solid" | "outline" | "soft" | "subtle"; size?: "xs" | "sm" | "md" | "lg" | "xl" };
    export const badge: (props?: BadgeProps) => string;
}

declare module "virtual:styleframe.css" {
    const css: string;
    export default css;
}
