import type { Generator } from '../../types';
import {
    transitionGenerator,
    borderGenerator,
    borderRadiusGenerator,
    boxShadowGenerator,
    breakpointsGenerator,
    breakpointsMixinsGenerator,
    colorsGenerator,
    componentsGenerator,
    elementsGenerator,
    scaleRatiosGenerator,
    sizeMultiplierGenerator,
    sizePercentagesGenerator,
    spacingGenerator,
    typographyColorGenerator,
    typographyContrastColorGenerator,
    typographyFontFamilyGenerator,
    typographyFontSizeGenerator,
    typographyFontWeightGenerator,
    typographyLetterSpacingGenerator,
    typographyLineHeightGenerator,
    paddingGenerator,
    marginGenerator,
    typographyTextAlignmentGenerator
} from '../../generators';

export const defaultGenerators: Generator<any>[] = [
    transitionGenerator,
    borderGenerator,
    borderRadiusGenerator,
    breakpointsGenerator,
    breakpointsMixinsGenerator,
    boxShadowGenerator,
    colorsGenerator,
    componentsGenerator,
    elementsGenerator,
    scaleRatiosGenerator,
    sizePercentagesGenerator,
    sizeMultiplierGenerator,
    spacingGenerator,
    marginGenerator,
    paddingGenerator,
    typographyColorGenerator,
    typographyContrastColorGenerator,
    typographyFontFamilyGenerator,
    typographyFontSizeGenerator,
    typographyFontWeightGenerator,
    typographyLineHeightGenerator,
    typographyLetterSpacingGenerator,
    typographyTextAlignmentGenerator
];
