import type { Resolver } from '../../types';
import {
    transitionResolver,
    borderRadiusResolver,
    borderResolver,
    boxShadowResolver,
    breakpointsResolver,
    colorsResolver,
    componentsResolver,
    elementsResolver,
    gridColumnsResolver,
    gridContainerResolver,
    gridGutterResolver,
    scaleRatiosResolver,
    sizeMultiplierResolver,
    sizePercentagesResolver,
    spacingResolver,
    marginResolver,
    paddingResolver,
    typographyColorResolver,
    typographyContrastColorResolver,
    typographyFontFamilyResolver,
    typographyFontSizeResolver,
    typographyFontWeightResolver,
    typographyLetterSpacingResolver,
    typographyLineHeightResolver,
    typographyTextAlignmentResolver
} from '../../resolvers';

export const defaultResolvers: Resolver<any, any>[] = [
    transitionResolver,
    borderResolver,
    borderRadiusResolver,
    breakpointsResolver,
    boxShadowResolver,
    colorsResolver,
    componentsResolver,
    elementsResolver,
    gridColumnsResolver,
    gridContainerResolver,
    gridGutterResolver,
    scaleRatiosResolver,
    sizePercentagesResolver,
    sizeMultiplierResolver,
    spacingResolver,
    marginResolver,
    paddingResolver,
    typographyColorResolver,
    typographyContrastColorResolver,
    typographyFontFamilyResolver,
    typographyFontSizeResolver,
    typographyFontWeightResolver,
    typographyLineHeightResolver,
    typographyLetterSpacingResolver,
    typographyTextAlignmentResolver
];
