#!/usr/bin/env node
/**
 * Maintains `src/vendor/` — the vendored upstream JSX element types that `JSX.IntrinsicElements`
 * is derived from. See `src/vendor/README.md` for why the types are vendored rather than depended
 * on.
 *
 *   node scripts/generate-jsx.mjs            re-sync from npm and rewrite the vendored files
 *   node scripts/generate-jsx.mjs --check    verify the tree matches the manifest (offline)
 *   node scripts/generate-jsx.mjs --check --fetch
 *                                            ...and that the manifest still matches npm
 *
 * `manifest.json` is the single input. The version lives there and nowhere else: the header of the
 * generated `.d.ts`, the provenance table in `README.md`, and the tarball this script fetches are
 * all derived from it. To move to a new upstream release, edit `version` in the manifest and run
 * the sync — nothing else is hand-edited.
 *
 * The vendored body is never modified. Reshaping the upstream happens in `../src/jsx-runtime.ts`,
 * which is the only seam.
 */

import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const DEFAULT_VENDOR_DIR = resolve(SCRIPT_DIR, "../src/vendor");

/** Marks the generated region of `README.md`. Everything else in that file is hand-written. */
const README_BEGIN =
  "<!-- generate:jsx:begin — generated by scripts/generate-jsx.mjs, do not edit -->";
const README_END = "<!-- generate:jsx:end -->";

/** Replaced by the first line number of the upstream body once the header's length is known. */
const BODY_START = "{{BODY_START}}";

class GenerateJsxError extends Error {}

function sha256(contents) {
  return createHash("sha256").update(contents).digest("hex");
}

function read(path) {
  return readFileSync(path, "utf8");
}

/**
 * Pulls the copyright line out of the upstream licence so it is never transcribed by hand. If
 * upstream restructures its licence this throws rather than silently emitting a header with a
 * missing attribution.
 */
function copyrightFrom(licence) {
  const line = licence
    .split("\n")
    .find((candidate) => /^copyright\s*\(c\)/i.test(candidate.trim()));
  if (!line) {
    throw new GenerateJsxError("no `Copyright (c) ...` line found in the upstream licence");
  }
  return line.trim();
}

/**
 * Indents the upstream licence into the JSDoc header. MIT requires the copyright notice and the
 * permission notice to travel with every substantial copy of the Software; carrying them inside the
 * file that *is* the copy satisfies that without a second file to keep in sync or lose.
 */
function renderNotice(licence) {
  return licence
    .trimEnd()
    .split("\n")
    .map((line) => (line.trim() === "" ? " *" : ` *   ${line}`))
    .join("\n");
}

function renderHeader(manifest, copyright) {
  const template = `// oxlint-disable typescript/no-redundant-type-constituents -- see the note below.
/**
 * VENDORED — DO NOT EDIT BY HAND.
 *
 * Source:  ${manifest.package}@${manifest.version} — ${manifest.source.types}, as published on npm
 * Project: ${manifest.repository}
 * License: ${manifest.license.spdx} — ${copyright}
 *
 * The upstream licence, in full. It is reproduced here rather than in a separate file because MIT
 * binds the notice to the copy, and the copy is this file:
 *
${renderNotice(manifest.license.notice)}
 *
 * This header is generated and everything from line ${BODY_START} onward is byte-identical to the
 * upstream file. Both halves are produced and verified by:
 *
 *   pnpm --filter @inkline/core generate:jsx          # re-sync from npm
 *   pnpm --filter @inkline/core generate:jsx:check    # verify nothing has drifted
 *
 * The version above is propagated from ./manifest.json, which is the only place it is written.
 * Editing it here does nothing except fail the check.
 *
 * These are the HTML/SVG/MathML element attribute types that \`JSX.IntrinsicElements\` is derived
 * from, through the \`Inklinified<T>\` alias in ../jsx-runtime.ts. That alias is the only place the
 * upstream is reshaped; this file is never edited locally.
 *
 * Vendored rather than depended on because \`${manifest.package}\` is a runtime package and
 * \`@inkline/core\` ships no runtime. See ./README.md for the rationale.
 *
 * The \`oxlint-disable\` above is the one concession the copy asks for. Upstream writes open unions
 * as \`"auto" | string\`, which \`no-redundant-type-constituents\` flags 11 times. It silences \`vp
 * lint\`; \`vp check\`'s type-aware pass reports the same 11 as warnings regardless — that pass does
 * not honour suppression comments. Both exit 0, so this is noise, not a gate.
 *
 * The \`THIS FILE IS GENERATED BY ./jsx-update.mjs\` banner immediately below belongs to upstream
 * and is copied verbatim with the rest of the body. It names Solid's own generator and Solid's own
 * \`pnpm jsx-sync-types\` script — neither exists here. The command to run in this repository is
 * \`generate:jsx\`, above.
 */
`;

  // The placeholder and its replacement both sit on one line, so substituting it cannot change the
  // line count. That is what lets the header state its own length without anyone maintaining it.
  const headerLines = template.split("\n").length - 1;
  return template.replace(BODY_START, String(headerLines + 1));
}

function renderReadmeBlock(manifest, copyright) {
  return [
    README_BEGIN,
    "",
    "| | |",
    "|---|---|",
    `| Source | \`${manifest.package}@${manifest.version}\`, file \`${manifest.source.types}\`, as published on npm |`,
    `| Upstream project | ${manifest.repository} |`,
    `| License | ${manifest.license.spdx} — ${copyright}, reproduced in full in the header of [\`${manifest.output.types}\`](./${manifest.output.types}) |`,
    `| Local changes | **None.** Everything below the generated header is byte-identical to upstream. |`,
    `| Body checksum | \`sha256:${manifest.integrity.types}\` |`,
    "",
    README_END,
  ].join("\n");
}

function spliceReadme(readme, block) {
  const start = readme.indexOf(README_BEGIN);
  const end = readme.indexOf(README_END);
  if (start === -1 || end === -1 || end < start) {
    throw new GenerateJsxError(
      `README.md is missing the \`${README_BEGIN}\` / \`${README_END}\` markers that delimit the generated provenance table`,
    );
  }
  return readme.slice(0, start) + block + readme.slice(end + README_END.length);
}

/**
 * Downloads the published tarball and returns the two files we vendor. Uses `npm pack` rather than
 * a direct registry fetch so the caller's registry, proxy and auth configuration all apply.
 */
function fetchUpstream(manifest) {
  const workdir = mkdtempSync(join(tmpdir(), "inkline-generate-jsx-"));
  try {
    const spec = `${manifest.package}@${manifest.version}`;
    const stdout = execFileSync("npm", ["pack", spec, "--silent", "--pack-destination", workdir], {
      encoding: "utf8",
    });
    const tarball = join(workdir, stdout.trim().split("\n").at(-1).trim());
    execFileSync("tar", ["-xzf", tarball, "-C", workdir]);
    return {
      types: read(join(workdir, "package", manifest.source.types)),
      licence: read(join(workdir, "package", manifest.license.source)),
    };
  } finally {
    rmSync(workdir, { recursive: true, force: true });
  }
}

export function sync(vendorDir = DEFAULT_VENDOR_DIR, log = console.log) {
  const manifest = JSON.parse(read(join(vendorDir, "manifest.json")));
  log(`fetching ${manifest.package}@${manifest.version} from npm…`);

  const upstream = fetchUpstream(manifest);
  const copyright = copyrightFrom(upstream.licence);
  const next = {
    ...manifest,
    license: { ...manifest.license, notice: upstream.licence },
    integrity: { types: sha256(upstream.types), license: sha256(upstream.licence) },
  };

  writeFileSync(join(vendorDir, next.output.types), renderHeader(next, copyright) + upstream.types);
  writeFileSync(join(vendorDir, "manifest.json"), `${JSON.stringify(next, null, 2)}\n`);
  writeFileSync(
    join(vendorDir, "README.md"),
    spliceReadme(read(join(vendorDir, "README.md")), renderReadmeBlock(next, copyright)),
  );

  log(`wrote ${next.output.types} (body sha256:${next.integrity.types})`);
  return next;
}

/**
 * Reports every way the vendored tree can disagree with its manifest. Offline by default: the
 * manifest's checksums are enough to catch a hand-edit to the body, and re-rendering the header and
 * the README block catches a hand-edit to either of those. `fetch` adds the one thing local state
 * cannot answer — whether the manifest itself still describes what npm publishes.
 */
export function check(vendorDir = DEFAULT_VENDOR_DIR, { fetch = false } = {}) {
  const problems = [];
  const manifest = JSON.parse(read(join(vendorDir, "manifest.json")));

  const licence = manifest.license.notice;
  const licenceHash = sha256(licence);
  if (licenceHash !== manifest.integrity.license) {
    problems.push(
      `the licence notice in the manifest is not the one it records (sha256:${licenceHash}, expected sha256:${manifest.integrity.license})`,
    );
  }

  const copyright = copyrightFrom(licence);
  const expectedHeader = renderHeader(manifest, copyright);
  const file = read(join(vendorDir, manifest.output.types));
  if (!file.startsWith(expectedHeader)) {
    problems.push(
      `${manifest.output.types} has a header that is not the one the manifest generates — re-run \`generate:jsx\` or revert the edit`,
    );
  } else {
    const bodyHash = sha256(file.slice(expectedHeader.length));
    if (bodyHash !== manifest.integrity.types) {
      problems.push(
        `${manifest.output.types} body does not match the manifest (sha256:${bodyHash}, expected sha256:${manifest.integrity.types})`,
      );
    }
  }

  if (!read(join(vendorDir, "README.md")).includes(renderReadmeBlock(manifest, copyright))) {
    problems.push("README.md's generated provenance table is stale");
  }

  if (fetch) {
    const upstream = fetchUpstream(manifest);
    if (sha256(upstream.types) !== manifest.integrity.types) {
      problems.push(
        `npm now publishes a different ${manifest.source.types} for ${manifest.package}@${manifest.version} than the manifest records`,
      );
    }
    if (sha256(upstream.licence) !== manifest.integrity.license) {
      problems.push(
        `npm now publishes a different ${manifest.source.license} for ${manifest.package}@${manifest.version} than the manifest records`,
      );
    }
  }

  return problems;
}

function main(argv) {
  const flags = new Set(argv);
  const vendorDirFlag = argv.indexOf("--dir");
  const vendorDir = vendorDirFlag === -1 ? DEFAULT_VENDOR_DIR : resolve(argv[vendorDirFlag + 1]);

  if (!flags.has("--check")) {
    sync(vendorDir);
    return 0;
  }

  const problems = check(vendorDir, { fetch: flags.has("--fetch") });
  if (problems.length > 0) {
    console.error("vendored JSX types have drifted:");
    for (const problem of problems) console.error(`  - ${problem}`);
    console.error("\nrun `pnpm --filter @inkline/core generate:jsx` to regenerate them.");
    return 1;
  }

  console.log("vendored JSX types match the manifest.");
  return 0;
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) {
  try {
    process.exitCode = main(process.argv.slice(2));
  } catch (error) {
    console.error(error instanceof GenerateJsxError ? `error: ${error.message}` : error);
    process.exitCode = 1;
  }
}
