import { useAlertTheme } from '@inkline/inkline/components/IAlert/theme';
export * from '@inkline/inkline/components/IAlert/theme';
import { useBadgeTheme } from '@inkline/inkline/components/IBadge/theme';
export * from '@inkline/inkline/components/IBadge/theme';
import { useBreadcrumbTheme } from '@inkline/inkline/components/IBreadcrumb/theme';
export * from '@inkline/inkline/components/IBreadcrumb/theme';
import { useBreadcrumbItemTheme } from '@inkline/inkline/components/IBreadcrumbItem/theme';
export * from '@inkline/inkline/components/IBreadcrumbItem/theme';

// export * from '@inkline/inkline/components/IBreadcrumb';
// export * from '@inkline/inkline/components/IBreadcrumbItem';
// export * from '@inkline/inkline/components/IButton';
// export * from '@inkline/inkline/components/IButtonGroup';
// export * from '@inkline/inkline/components/ICard';
// export * from '@inkline/inkline/components/ICheckbox';
// export * from '@inkline/inkline/components/ICheckboxButtons';
// export * from '@inkline/inkline/components/ICheckboxGroup';
// export * from '@inkline/inkline/components/ICollapsible';
// export * from '@inkline/inkline/components/ICollapsibleItem';
// export * from '@inkline/inkline/components/IColumn';
// export * from '@inkline/inkline/components/IContainer';
// export * from '@inkline/inkline/components/IDropdown';
// export * from '@inkline/inkline/components/IDropdownDivider';
// export * from '@inkline/inkline/components/IDropdownItem';
// export * from '@inkline/inkline/components/IExpandTransition';
// export * from '@inkline/inkline/components/IForm';
// export * from '@inkline/inkline/components/IFormGroup';
// export * from '@inkline/inkline/components/IFormError';
// export * from '@inkline/inkline/components/IFormLabel';
// export * from '@inkline/inkline/components/IHamburgerMenu';
// export * from '@inkline/inkline/components/IHeader';
// export * from '@inkline/inkline/components/IIcon';
// export * from '@inkline/inkline/components/IInput';
// export * from '@inkline/inkline/components/ILayout';
// export * from '@inkline/inkline/components/ILayoutAside';
// export * from '@inkline/inkline/components/ILayoutContent';
// export * from '@inkline/inkline/components/ILayoutFooter';
// export * from '@inkline/inkline/components/ILayoutHeader';
// export * from '@inkline/inkline/components/IListGroup';
// export * from '@inkline/inkline/components/IListGroupItem';
// export * from '@inkline/inkline/components/ILoader';
// export * from '@inkline/inkline/components/IMark';
// export * from '@inkline/inkline/components/IMedia';
// export * from '@inkline/inkline/components/IModal';
// export * from '@inkline/inkline/components/IModalContainer';
// export * from '@inkline/inkline/components/INav';
// export * from '@inkline/inkline/components/INavItem';
// export * from '@inkline/inkline/components/INavbar';
// export * from '@inkline/inkline/components/INavbarBrand';
// export * from '@inkline/inkline/components/INavbarCollapsible';
// export * from '@inkline/inkline/components/INumberInput';
// export * from '@inkline/inkline/components/IPagination';
// export * from '@inkline/inkline/components/IPopover';
// export * from '@inkline/inkline/components/IProgress';
// export * from '@inkline/inkline/components/IProgressBar';
// export * from '@inkline/inkline/components/IRadio';
// export * from '@inkline/inkline/components/IRadioButtons';
// export * from '@inkline/inkline/components/IRadioGroup';
// export * from '@inkline/inkline/components/IRow';
// export * from '@inkline/inkline/components/ISelect';
// export * from '@inkline/inkline/components/ISelectOption';
// export * from '@inkline/inkline/components/ISidebar';
// export * from '@inkline/inkline/components/ITable';
// export * from '@inkline/inkline/components/ITabs';
// export * from '@inkline/inkline/components/ITab';
// export * from '@inkline/inkline/components/ITabTitle';
// export * from '@inkline/inkline/components/ITextarea';
// export * from '@inkline/inkline/components/IToast';
// export * from '@inkline/inkline/components/IToastContainer';
// export * from '@inkline/inkline/components/IToggle';
// export * from '@inkline/inkline/components/ITooltip';
// export * from '@inkline/inkline/components/utils';

export function useComponentThemes() {
    useAlertTheme();
    useBadgeTheme();
    useBreadcrumbTheme();
    useBreadcrumbItemTheme();
}
