#!/usr/bin/env node
/**
 * Derives `src/core/aria-attributes.generated.ts` — the set of ARIA attribute names INK0072 checks
 * a misspelling against — from `@inkline/core`'s vendored JSX element types.
 *
 *   node --experimental-strip-types scripts/gen-aria-attributes.ts            rewrite the module
 *   node --experimental-strip-types scripts/gen-aria-attributes.ts --check    verify it has not drifted
 *
 * Why derived rather than hand-listed: the same vendored file is what types `JSX.IntrinsicElements`
 * for authors, so the checker and the type surface cannot disagree about what ARIA is, and a
 * `generate:jsx` re-sync that adds or removes an attribute shows up here as a diff instead of
 * rotting quietly. The list is checked in (not read at runtime) because `@inkline/core` publishes
 * only `dist/` — `src/vendor/` does not exist for an installed consumer — and because the compiler
 * must not pay a 168 KB `.d.ts` parse to answer a set-membership question.
 *
 * The `--check` mode is what makes the derivation load-bearing; it runs as a unit test
 * (`src/core/aria-attributes.test.ts`), so a stale copy fails the suite rather than shipping.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import * as ts from "typescript";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));

/** The vendored upstream surface `JSX.IntrinsicElements` is derived from. See `core/core/src/vendor/`. */
export const DEFAULT_SOURCE = resolve(SCRIPT_DIR, "../../core/src/vendor/jsx-intrinsics.d.ts");
export const DEFAULT_OUTPUT = resolve(SCRIPT_DIR, "../src/core/aria-attributes.generated.ts");

/**
 * Every `"aria-…"` property name declared anywhere in the vendored types, via the AST rather than a
 * regex over the text. Deliberately not scoped to the `AriaAttributes` interface: upstream is free
 * to move or split it, and a scoped reader would silently return a short list where a whole-file
 * reader returns the same answer.
 */
export function extractAriaAttributes(source: string, fileName = "jsx-intrinsics.d.ts"): string[] {
  const sourceFile = ts.createSourceFile(fileName, source, ts.ScriptTarget.Latest, true);
  const names = new Set<string>();

  const visit = (node: ts.Node): void => {
    if (
      ts.isPropertySignature(node) &&
      ts.isStringLiteral(node.name) &&
      node.name.text.startsWith("aria-")
    ) {
      names.add(node.name.text);
    }
    ts.forEachChild(node, visit);
  };
  visit(sourceFile);

  return [...names].sort();
}

export function render(attributes: readonly string[]): string {
  return `// GENERATED BY scripts/gen-aria-attributes.ts — DO NOT EDIT BY HAND.
//
// Derived from \`@inkline/core\`'s vendored JSX element types, the same file that types
// \`JSX.IntrinsicElements\` for authors. Re-run after \`generate:jsx\`:
//
//   pnpm --filter @inkline/compiler generate:aria
//
// \`src/core/aria-attributes.test.ts\` fails if this file and that one disagree.

/** The ${attributes.length} ARIA attribute names the vendored upstream declares. */
export const ARIA_ATTRIBUTES: readonly string[] = [
${attributes.map((name) => `  "${name}",`).join("\n")}
];
`;
}

export function generate(source = DEFAULT_SOURCE): string {
  return render(extractAriaAttributes(readFileSync(source, "utf8"), source));
}

/** Every way the checked-in module can disagree with the vendored types. Empty means no drift. */
export function check(source = DEFAULT_SOURCE, output = DEFAULT_OUTPUT): string[] {
  const expected = generate(source);
  const actual = readFileSync(output, "utf8");
  return expected === actual
    ? []
    : [
        "src/core/aria-attributes.generated.ts is not what the vendored JSX types generate — " +
          "run `pnpm --filter @inkline/compiler generate:aria`",
      ];
}

function main(argv: readonly string[]): number {
  if (!argv.includes("--check")) {
    writeFileSync(DEFAULT_OUTPUT, generate());
    console.log(`wrote ${DEFAULT_OUTPUT}`);
    return 0;
  }

  const problems = check();
  for (const problem of problems) console.error(`error: ${problem}`);
  if (problems.length > 0) return 1;

  console.log("ARIA attribute set matches the vendored JSX types.");
  return 0;
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) {
  process.exitCode = main(process.argv.slice(2));
}
