export { default as ImagesAlignmentCenterExample } from '@inkline/inkline/stories/core/images/alignment-center.vue';
export { default as ImagesAlignmentLeftExample } from '@inkline/inkline/stories/core/images/alignment-left.vue';
export { default as ImagesAlignmentMarginAutoExample } from '@inkline/inkline/stories/core/images/alignment-margin-auto.vue';
export { default as ImagesAlignmentRightExample } from '@inkline/inkline/stories/core/images/alignment-right.vue';
export { default as ImagesFluidExample } from '@inkline/inkline/stories/core/images/fluid.vue';
export { default as ImagesPictureExample } from '@inkline/inkline/stories/core/images/picture.vue';
export { default as ImagesPolaroidExample } from '@inkline/inkline/stories/core/images/polaroid.vue';
export { default as ImagesResponsiveExample } from '@inkline/inkline/stories/core/images/responsive.vue';
export { default as ImagesThumbnailExample } from '@inkline/inkline/stories/core/images/thumbnail.vue';
