// export * from './IBreadcrumb';
// export * from './IBreadcrumbItem';
// export * from './IButton';
// export * from './IButtonGroup';
// export * from './ICard';
// export * from './ICheckbox';
// export * from './ICheckboxButtons';
// export * from './ICheckboxGroup';
// export * from './ICollapsible';
// export * from './ICollapsibleItem';
// export * from './IColumn';
// export * from './IContainer';
// export * from './IDropdown';
// export * from './IDropdownDivider';
// export * from './IDropdownItem';
// export * from './IExpandTransition';
// export * from './IForm';
// export * from './IFormGroup';
// export * from './IFormError';
// export * from './IFormLabel';
// export * from './IHamburgerMenu';
// export * from './IHeader';
// export * from './IIcon';
// export * from './IInput';
// export * from './ILayout';
// export * from './ILayoutAside';
// export * from './ILayoutContent';
// export * from './ILayoutFooter';
// export * from './ILayoutHeader';
// export * from './IListGroup';
// export * from './IListGroupItem';
// export * from './ILoader';
// export * from './IMark';
// export * from './IMedia';
// export * from './IModal';
// export * from './IModalContainer';
// export * from './INav';
// export * from './INavItem';
// export * from './INavbar';
// export * from './INavbarBrand';
// export * from './INavbarCollapsible';
// export * from './INumberInput';
// export * from './IPagination';
// export * from './IPopover';
// export * from './IProgress';
// export * from './IProgressBar';
// export * from './IRadio';
// export * from './IRadioButtons';
// export * from './IRadioGroup';
// export * from './IRow';
// export * from './ISelect';
// export * from './ISelectOption';
// export * from './ISidebar';
// export * from './ITable';
// export * from './ITabs';
// export * from './ITab';
// export * from './ITabTitle';
// export * from './ITextarea';
// export * from './IToast';
// export * from './IToastContainer';
// export * from './IToggle';
// export * from './ITooltip';
// export * from './utils';

import { useAlertTheme } from './IAlert/theme';
import { useBadgeTheme } from './IBadge/theme';
import { useBreadcrumbTheme } from './IBreadcrumb/theme';
import { useBreadcrumbItemTheme } from './IBreadcrumbItem/theme';
import { useButtonTheme } from './IButton/theme';
import { useButtonGroupTheme } from './IButtonGroup/theme';
import { useCardTheme } from './ICard/theme';

export function useThemeComponents() {
    useAlertTheme();
    useBadgeTheme();
    useBreadcrumbTheme();
    useBreadcrumbItemTheme();
    useButtonTheme();
    useButtonGroupTheme();
    useCardTheme();
}
