<template>
    <IContainer>
        <IRow>
            <IColumn></IColumn>
        </IRow>
        <IRow>
            <IColumn></IColumn>
            <IColumn></IColumn>
        </IRow>
        <IRow>
            <IColumn></IColumn>
            <IColumn></IColumn>
            <IColumn></IColumn>
        </IRow>
        <IRow>
            <IColumn></IColumn>
            <IColumn></IColumn>
            <IColumn></IColumn>
            <IColumn></IColumn>
        </IRow>
        <IRow>
            <IColumn></IColumn>
            <IColumn></IColumn>
            <IColumn></IColumn>
            <IColumn></IColumn>
            <IColumn></IColumn>
        </IRow>
        <IRow>
            <IColumn></IColumn>
            <IColumn></IColumn>
            <IColumn></IColumn>
            <IColumn></IColumn>
            <IColumn></IColumn>
            <IColumn></IColumn>
        </IRow>
    </IContainer>
</template>
