export const BANNER =
  "// AUTO-GENERATED by @inkline/storybook — DO NOT EDIT.\n" +
  "// Edit the single-source definition in ui/core/stories/ and regenerate.\n";

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

/**
 * Guards values that are emitted as raw code (not string literals): the
 * component binding and every story export name. An invalid identifier would
 * produce a story file that fails to parse, so fail fast with a clear message.
 */
export function assertIdentifier(value: string, label: string): void {
  if (!IDENTIFIER.test(value)) {
    throw new Error(
      `Invalid ${label} ${JSON.stringify(value)}: must be a valid JavaScript identifier.`,
    );
  }
}

/** Compact, deterministic serialization for `args`/`argTypes` object literals. */
export function serializeArgs(value: unknown): string {
  return JSON.stringify(value);
}
