import { useNormalizeTheme } from '@inkline/inkline/global/normalize/theme';
export * from '@inkline/inkline/global/normalize/theme';
import { useATheme } from '@inkline/inkline/global/a/theme';
export * from '@inkline/inkline/global/a/theme';
import { useAbbrTheme } from '@inkline/inkline/global/abbr/theme';
export * from '@inkline/inkline/global/abbr/theme';
import { useAddressTheme } from '@inkline/inkline/global/address/theme';
export * from '@inkline/inkline/global/address/theme';
import { useBlockquoteTheme } from '@inkline/inkline/global/blockquote/theme';
export * from '@inkline/inkline/global/blockquote/theme';
import { useBodyTheme } from '@inkline/inkline/global/body/theme';
export * from '@inkline/inkline/global/body/theme';
import { useCaptionTheme } from '@inkline/inkline/global/caption/theme';
export * from '@inkline/inkline/global/caption/theme';
import { useCodeTheme } from '@inkline/inkline/global/code/theme';
export * from '@inkline/inkline/global/code/theme';
import { useDisplayTheme } from '@inkline/inkline/global/display/theme';
export * from '@inkline/inkline/global/display/theme';
import { useDlTheme } from '@inkline/inkline/global/dl/theme';
export * from '@inkline/inkline/global/dl/theme';
import { useHeadingTheme } from '@inkline/inkline/global/heading/theme';
export * from '@inkline/inkline/global/heading/theme';
import { useHrTheme } from '@inkline/inkline/global/hr/theme';
export * from '@inkline/inkline/global/hr/theme';
import { useIframeTheme } from '@inkline/inkline/global/iframe/theme';
export * from '@inkline/inkline/global/iframe/theme';
import { useKbdTheme } from '@inkline/inkline/global/kbd/theme';
export * from '@inkline/inkline/global/kbd/theme';
import { useLegendTheme } from '@inkline/inkline/global/legend/theme';
export * from '@inkline/inkline/global/legend/theme';
import { useMarkTheme } from '@inkline/inkline/global/mark/theme';
export * from '@inkline/inkline/global/mark/theme';
import { useOlTheme } from '@inkline/inkline/global/ol/theme';
export * from '@inkline/inkline/global/ol/theme';
import { useOutputTheme } from '@inkline/inkline/global/output/theme';
export * from '@inkline/inkline/global/output/theme';
import { useParagraphTheme } from '@inkline/inkline/global/p/theme';
export * from '@inkline/inkline/global/p/theme';
import { usePreTheme } from '@inkline/inkline/global/pre/theme';
export * from '@inkline/inkline/global/pre/theme';
import { useSampTheme } from '@inkline/inkline/global/samp/theme';
export * from '@inkline/inkline/global/samp/theme';
import { useSummaryTheme } from '@inkline/inkline/global/summary/theme';
export * from '@inkline/inkline/global/summary/theme';
import { useUlTheme } from '@inkline/inkline/global/ul/theme';
export * from '@inkline/inkline/global/ul/theme';
import { useTransitionsTheme } from '@inkline/inkline/global/transition/theme';
export * from '@inkline/inkline/global/transition/theme';

export function useElementThemes() {
    useNormalizeTheme();
    useATheme();
    useAbbrTheme();
    useAddressTheme();
    useBlockquoteTheme();
    useBodyTheme();
    useCaptionTheme();
    useCodeTheme();
    useDisplayTheme();
    useDlTheme();
    useHeadingTheme();
    useHrTheme();
    useIframeTheme();
    useKbdTheme();
    useLegendTheme();
    useMarkTheme();
    useOlTheme();
    useOutputTheme();
    useParagraphTheme();
    usePreTheme();
    useSampTheme();
    useSummaryTheme();
    useUlTheme();
    useTransitionsTheme();
}
