import ColorBasicBackgroundExample from './basic-background.vue';
import ColorBasicBlueBackgroundExample from './basic-blue-background.vue';
import ColorBasicBlueTextExample from './basic-blue-text.vue';
import ColorBasicGreenBackgroundExample from './basic-green-background.vue';
import ColorBasicGreenTextExample from './basic-green-text.vue';
import ColorBasicOrangeBackgroundExample from './basic-orange-background.vue';
import ColorBasicOrangeTextExample from './basic-orange-text.vue';
import ColorBasicPinkBackgroundExample from './basic-pink-background.vue';
import ColorBasicPinkTextExample from './basic-pink-text.vue';
import ColorBasicPurpleBackgroundExample from './basic-purple-background.vue';
import ColorBasicPurpleTextExample from './basic-purple-text.vue';
import ColorBasicRedBackgroundExample from './basic-red-background.vue';
import ColorBasicRedTextExample from './basic-red-text.vue';
import ColorBasicTealBackgroundExample from './basic-teal-background.vue';
import ColorBasicTealTextExample from './basic-teal-text.vue';
import ColorBasicTextExample from './basic-text.vue';
import ColorBasicYellowBackgroundExample from './basic-yellow-background.vue';
import ColorBasicYellowTextExample from './basic-yellow-text.vue';
import ColorBrandBackgroundExample from './brand-background.vue';
import ColorBrandDarkBackgroundExample from './brand-dark-background.vue';
import ColorBrandDarkTextExample from './brand-dark-text.vue';
import ColorBrandLightBackgroundExample from './brand-light-background.vue';
import ColorBrandLightTextExample from './brand-light-text.vue';
import ColorBrandPrimaryBackgroundExample from './brand-primary-background.vue';
import ColorBrandPrimaryTextExample from './brand-primary-text.vue';
import ColorBrandSecondaryBackgroundExample from './brand-secondary-background.vue';
import ColorBrandSecondaryTextExample from './brand-secondary-text.vue';
import ColorBrandTextExample from './brand-text.vue';
import ColorNeutralBackgroundExample from './neutral-background.vue';
import ColorNeutralTextExample from './neutral-text.vue';
import ColorSocialBackgroundExample from './social-background.vue';
import ColorSocialTextExample from './social-text.vue';
import ColorStateBackgroundExample from './state-background.vue';
import ColorStateDangerBackgroundExample from './state-danger-background.vue';
import ColorStateDangerTextExample from './state-danger-text.vue';
import ColorStateInfoBackgroundExample from './state-info-background.vue';
import ColorStateInfoTextExample from './state-info-text.vue';
import ColorStateSuccessBackgroundExample from './state-success-background.vue';
import ColorStateSuccessTextExample from './state-success-text.vue';
import ColorStateTextExample from './state-text.vue';
import ColorStateWarningBackgroundExample from './state-warning-background.vue';
import ColorStateWarningTextExample from './state-warning-text.vue';

export default {
    title: 'Utilities/Color'
};

export const BasicBackground = () => ColorBasicBackgroundExample;
export const BasicBlueBackground = () => ColorBasicBlueBackgroundExample;
export const BasicBlueText = () => ColorBasicBlueTextExample;
export const BasicGreenBackground = () => ColorBasicGreenBackgroundExample;
export const BasicGreenText = () => ColorBasicGreenTextExample;
export const BasicOrangeBackground = () => ColorBasicOrangeBackgroundExample;
export const BasicOrangeText = () => ColorBasicOrangeTextExample;
export const BasicPinkBackground = () => ColorBasicPinkBackgroundExample;
export const BasicPinkText = () => ColorBasicPinkTextExample;
export const BasicPurpleBackground = () => ColorBasicPurpleBackgroundExample;
export const BasicPurpleText = () => ColorBasicPurpleTextExample;
export const BasicRedBackground = () => ColorBasicRedBackgroundExample;
export const BasicRedText = () => ColorBasicRedTextExample;
export const BasicTealBackground = () => ColorBasicTealBackgroundExample;
export const BasicTealText = () => ColorBasicTealTextExample;
export const BasicText = () => ColorBasicTextExample;
export const BasicYellowBackground = () => ColorBasicYellowBackgroundExample;
export const BasicYellowText = () => ColorBasicYellowTextExample;
export const BrandBackground = () => ColorBrandBackgroundExample;
export const BrandDarkBackground = () => ColorBrandDarkBackgroundExample;
export const BrandDarkText = () => ColorBrandDarkTextExample;
export const BrandLightBackground = () => ColorBrandLightBackgroundExample;
export const BrandLightText = () => ColorBrandLightTextExample;
export const BrandPrimaryBackground = () => ColorBrandPrimaryBackgroundExample;
export const BrandPrimaryText = () => ColorBrandPrimaryTextExample;
export const BrandSecondaryBackground = () => ColorBrandSecondaryBackgroundExample;
export const BrandSecondaryText = () => ColorBrandSecondaryTextExample;
export const BrandText = () => ColorBrandTextExample;
export const NeutralBackground = () => ColorNeutralBackgroundExample;
export const NeutralText = () => ColorNeutralTextExample;
export const SocialBackground = () => ColorSocialBackgroundExample;
export const SocialText = () => ColorSocialTextExample;
export const StateBackground = () => ColorStateBackgroundExample;
export const StateDangerBackground = () => ColorStateDangerBackgroundExample;
export const StateDangerText = () => ColorStateDangerTextExample;
export const StateInfoBackground = () => ColorStateInfoBackgroundExample;
export const StateInfoText = () => ColorStateInfoTextExample;
export const StateSuccessBackground = () => ColorStateSuccessBackgroundExample;
export const StateSuccessText = () => ColorStateSuccessTextExample;
export const StateText = () => ColorStateTextExample;
export const StateWarningBackground = () => ColorStateWarningBackgroundExample;
export const StateWarningText = () => ColorStateWarningTextExample;
