name: Build
on: [ 'push', 'pull_request' ]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: [ '14' ]
        name: Node ${{ matrix.node }}
        steps:
            -   name: Set up repository
                uses: actions/checkout@v2
            -   name: Set up node
                uses: actions/setup-node@v1
                with:
                    node-version: ${{ matrix.node }}
            -   run: npm install
            -   run: npm run build
            -   run: npm run lint
            -   run: npm run test
            -   name: Coveralls
                uses: coverallsapp/github-action@master
                with:
                    path-to-lcov: coverage/lcov.info
                    github-token: ${{ secrets.GITHUB_TOKEN }}
