import { spawnSync } from "node:child_process";
import { cpSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { afterEach, describe, expect, it } from "vitest";

/**
 * `src/vendor/` is generated by `scripts/generate-jsx.mjs` from `src/vendor/manifest.json`. Running
 * its check mode here is what makes a hand-edit to the vendored copy impossible to land quietly:
 * the drift shows up as a failing unit test in the existing CI job, with no workflow of its own.
 *
 * Each tampering case exists because a passing checker proves nothing on its own. If the check
 * cannot fail, it is not a gate.
 */

const SCRIPT = resolve(import.meta.dirname, "../scripts/generate-jsx.mjs");
const VENDOR_DIR = resolve(import.meta.dirname, "vendor");

const scratchDirs: string[] = [];

afterEach(() => {
  for (const dir of scratchDirs.splice(0)) rmSync(dir, { recursive: true, force: true });
});

function check(dir: string) {
  const result = spawnSync("node", [SCRIPT, "--check", "--dir", dir], { encoding: "utf8" });
  return { status: result.status, output: result.stdout + result.stderr };
}

/** A throwaway copy of the vendored tree, with one file corrupted the way a stray edit would. */
function tamperedCopy(file: string, corrupt: (contents: string) => string) {
  const dir = mkdtempSync(join(tmpdir(), "inkline-vendor-integrity-"));
  scratchDirs.push(dir);
  cpSync(VENDOR_DIR, dir, { recursive: true });
  writeFileSync(join(dir, file), corrupt(readFileSync(join(dir, file), "utf8")));
  return dir;
}

describe("vendored JSX types", () => {
  it("matches the manifest that generated them", () => {
    const { status, output } = check(VENDOR_DIR);
    expect(output).toContain("match the manifest");
    expect(status).toBe(0);
  });

  it("fails the check when the upstream body is edited", () => {
    const dir = tamperedCopy(
      "jsx-intrinsics.d.ts",
      (contents) => `${contents}\nexport type Sneaky = 1;\n`,
    );
    const { status, output } = check(dir);

    expect(output).toContain("body does not match the manifest");
    expect(status).toBe(1);
  });

  it("fails the check when the generated header is edited", () => {
    const dir = tamperedCopy("jsx-intrinsics.d.ts", (contents) =>
      contents.replace("VENDORED — DO NOT EDIT BY HAND.", "VENDORED — lightly edited by hand."),
    );
    const { status, output } = check(dir);

    expect(output).toContain("header that is not the one the manifest generates");
    expect(status).toBe(1);
  });

  it("fails the check when the version is edited anywhere but the manifest", () => {
    const dir = tamperedCopy("jsx-intrinsics.d.ts", (contents) =>
      contents.replace("solid-js@", "solid-js@9.9.9 — was "),
    );

    expect(check(dir).status).toBe(1);
  });

  it("fails the check when the generated provenance table goes stale", () => {
    const dir = tamperedCopy("README.md", (contents) =>
      contents.replace("| Local changes | **None.**", "| Local changes | **Some.**"),
    );
    const { status, output } = check(dir);

    expect(output).toContain("provenance table is stale");
    expect(status).toBe(1);
  });

  it("fails the check when the MIT notice is weakened in the manifest", () => {
    const dir = tamperedCopy("manifest.json", (contents) =>
      contents.replace("MIT License", "MIT-ish License"),
    );
    const { status, output } = check(dir);

    expect(output).toContain("licence notice in the manifest is not the one it records");
    expect(status).toBe(1);
  });

  it("fails the check when the MIT notice is stripped from the generated header", () => {
    const dir = tamperedCopy("jsx-intrinsics.d.ts", (contents) =>
      contents.replace('THE SOFTWARE IS PROVIDED "AS IS"', "THE SOFTWARE IS PROVIDED"),
    );

    expect(check(dir).status).toBe(1);
  });
});
